- moving line around icons on hover/resources/css/index.css
turned into dark them || can also toggle btn between the light and dark theme || UI++
> Converted into dark theme || Intersting UI

- java/Tic_Tac_Toe_with_Computer.java
This is a java program that serves as a tic-tac-toe game between user and computer. Here user just need to enter the coordinates of the place where-ever he/she wishes to put his/her mark. Computer automatically takes its turn and the game goes on.
_Please don't forget to change the class name from **Main** if it throws error._
> Tic_Tac_Toe_with_Computer.java

- java/linearSearch.java
linear search algorithm in java
> Linear Search

- java/NumberGuessingGame.java
This is a number guessing game written in java language. In this game the computer randomly chooses a number and the user has to guess it. If the number is exactly same to the number generated by the computer then the user wins the game else the computer give the hint that weather the actual number is smaller or lager than the guessed number.
_Please don't forget to change the class name from **Main** if it throws error._
> NumberGuessingGame.java

- java/Library.java
This is a java program that works similar to a library software.
Here a user can:
View the available books.
1. Add a book
2. Issue a book
3. Return a book
This helps in maintaining track of books in library.
_Please don't forget to change the class name from **Main** if it throws error._
> Library.java

- C++/Factorial_sum.cpp
This is a C++ code to compute sum of the factorial of a given number starting from 1.
_For example,_ if any number **n** is given as input then the code will return **sum= 1! +2! +3! +4! ... n!**.
[n = 5, sum = 153]
> Factorial_sum.cpp

- C++/Amount_in_Words.cpp
This is a C++ program that converts an amount _(in integer, upto 999999)_ into words. 
[i/p –**231504**, output –**2 lakh 31 thousand 5 hundred and four only**]
> Amount_in_Words.cpp

- C++/Power_of_2.cpp
This is a C++ program to check weather a number is a **power of 2** or not using **logical operators.**
> Power_of_2.cpp

- C++/sliding-window.cpp
added problem of sliding window
> added sliding window

- C++/diagonalTraversalOfBinaryTree.cpp
Added C++ program for diagonal traversal of binary tree
> diagonal traversal of binary tree

- java/TriplyLinkedList.java
Triply Linked List in Java by SanketJ29
> Create Triply Linked List using Java

- C++/mergesort.cpp
> Added Merge Sort

- C++/Factorial_recursion.cpp
This is a C++ program to find **factorial** of a _user defined number_ using **recursion.**
> Factorial_recursion.cpp

- C++/selection_sort
I added a selection sort program in your repo. please accept it!
> Create selection_sort program

- C++/Sort012.cpp
added algorithm to sort 0 and 1
> Added Sort01 Algorithm

- java/CircularLL.java
I have created circular linked list implementation in java folder with name CircularLL.java
> CircularLL.java is created for circular linked list implementation

- HTML,CSS/tictactoe.html
my contribution for hactoberfest2022
> tic tac toe game using front end technologies

- C++/finabonaccirec.cpp
I have added a c++ program that tells the nth term of the Fibonacci series using recursion. Please accept my pull request.
> Added fibonacci series algorithm using recursion

- C++/BinarySearch.cpp
Fixes #76 
Added Binary Search Program
> Add BinarySearch.cpp

- java/PalindromeFOR.java
> Added Palindrome using FOR

- python/guessing_no.py
add label "hacktoberfest-accepted" before mering
> no guessing game

- C++/Longest Increasing Subsequence.cpp
Hi, can you please add this file in your repository. Thanks in advance :)
> Create Longest Increasing Subsequence.cpp

- C++/lis_and_lds.cpp
Hey **@ratnesh-maurya** 
Added **algo** to find **LIS** and **LDS** in **C++**.
Please review and merge.
**Thanks.**
> Added Longest Increasing Subsequence And Longest Decreasing Subsequence

- C++/Kth Largest Element in an Array.cpp
Please review my code merge it and accept my pull request
> Kth Largest Element in an Array.cpp

- C++/Fibbonacci.cpp
- C++/SayDigits.cpp
- C++/climbStairs.cpp
- C++/factroial.cpp
- C++/power.cpp
simple problems solved on recursion.
> recursion problems added

- C++/recursion/Fibbonacci.cpp
- C++/recursion/InversionCount.java
- C++/recursion/MergeSort.java
- C++/recursion/SayDigits.cpp
- C++/recursion/binarySearch.cpp
- C++/recursion/bubbleSort.cpp
- C++/recursion/climbStairs.cpp
- C++/recursion/exponent.cpp
- C++/recursion/factroial.cpp
- C++/recursion/keypad.cpp
- C++/recursion/linearSearch.cpp
- C++/recursion/mergeSort.cpp
- C++/recursion/palindromeCheck.cpp
- C++/recursion/power.cpp
- C++/recursion/quickSort.cpp
- C++/recursion/reverseString.cpp
- C++/recursion/sortedArray.cpp
- C++/recursion/subsequences.cpp
- C++/recursion/subsets.cpp
- C++/recursion/sum.cpp
- C++/recursion/walkingExample.cpp
recursive solution to simple problems .
> 21 basic problems added

- C++/coloured-ball revisited
- C++/skyline problem leetcode
- C++/spell check
Codeforce Solution of Coloured ball : revisited
> Create coloured-ball revisited

- java/Right Pascal Triangle
> Create Right Pascal Triangle

- difference_btw_highest_and_lowest_occurence.cpp
Difference btw highest and lowest occurence
> Difference btw highest and lowest occurence

- C++/Fibonacci_series.cpp
Sir, I have added the Fibonacci sequence in C++.I hope you will like it and merge in the main branch.
Any feedback please let me know
> Add Fibonacci Series in c++

- C++/kthAncestor.cpp
> adding kthAncestor.cpp

- ToDoListinator.py
This program helps you set up tasks in the form of a ToDo List and checks them off when you complete them.
> To-Do List Creator

- str_prg.py
This program performs multiple simple and complex operations on a given piece of text.
> Word Slicer

- calc.py
This is a simple calculator program, created using python's math module.
> Calculator

- C++/Floyd_cycle_detection_for_linked_list.cpp
- C++/Sieve_of_eratosthenes.cpp
Hey @ratnesh-maurya this is in refrance to #137
> Added floyd's cycle detection and sieve of eratosthenes aglorithms

- C++/diamond_pattern.cpp
diamond pattern of stars : 
*
***
*****
***
*
please do add hacktoberfest and hacktoberfest accepted tag before merging the PR.
Thanks :)
> added diamond_pattern.cpp

- C++/PermutationString.cpp
Added Permutation String in C++ programs which prints the possible permutations of a given string.
> Addded PermutationString

- C++/Breadth First Search Algorithm.cpp
Added Breadth First Search Code in C++
>  Breadth First Search Algorithm.cpp

- C/alphabet_pyramid.c
- C/factorial.c
- C/fibonacci.c
- C/prime_no_between.c
- C/rock_paper_scissor.c
In this commit I have added programs in the C programming language
> c-programs-added

- C/remove duplicate node in SLL
plz label with hacktoberfest 2022
> remove duplicate

- java/Merge Sorted Linked List.java
- java/Remove Nth node from end.java
Java program along with problem link of linked list problem.
> Create Merge Sorted Linked List.java

- C++/Longest_substring_without_repeating.cpp
- C++/minimum refuling stations.cpp
> Nice question asked multiple times in interview

- JS/2048-game/index.html
- JS/2048-game/script.js
- JS/2048-game/style.css
2048 tile game using JS, HTML/CSS.
> Issue #193

- python/Python Fundamental for Data Science/addTitleLabel_grafik.py
- python/Python Fundamental for Data Science/barChart.py
- python/Python Fundamental for Data Science/data_type.py
- python/Python Fundamental for Data Science/elif.py
- python/Python Fundamental for Data Science/for.py
- python/Python Fundamental for Data Science/function.py
- python/Python Fundamental for Data Science/hello.py
- python/Python Fundamental for Data Science/if.py
- python/Python Fundamental for Data Science/if_else.py
- python/Python Fundamental for Data Science/import_allModule.py
- python/Python Fundamental for Data Science/import_funtion.py
- python/Python Fundamental for Data Science/import_package.py
- python/Python Fundamental for Data Science/komentar.py
- python/Python Fundamental for Data Science/modulus.py
- python/Python Fundamental for Data Science/nested_if.py
- python/Python Fundamental for Data Science/operasi_mtk.py
- python/Python Fundamental for Data Science/param_Grafik.py
- python/Python Fundamental for Data Science/parameter_function.py
- python/Python Fundamental for Data Science/read_fileCSVPandas.py
- python/Python Fundamental for Data Science/read_fileText.py
- python/Python Fundamental for Data Science/renamemodul_import.py
- python/Python Fundamental for Data Science/returnvalue_function.py
- python/Python Fundamental for Data Science/while.py
> add python profesional for data science

- C++/deletefile.cpp
please gave hacktoberfest-accepted label in this repo
> Code in C++ language to delete a file from current directory

- C++/204_Count_Primes.cpp
- C++/54_Spiral_Matrix.cpp
Hi, I've added solutions for Spiral Matrix and Count Primes problems available on Leetcode in CPP
> Added Spiral Matrix and Count Prime

- insertion.cpp
Implemented insertion and deletion in a linked list at any Position.
> Insertion and Deletion in linked-list using c++

- C++/34_Find_First_and_Last_Position_of_Element_in_Sorted_Array.cpp
Solution and pseudocode to the following question
Given an array of integers nums sorted in ascending order, find the starting and ending position of a given target value. If target is not found in the array, return [-1, -1].
> Added 34_Find_First_and_Last_Position_of_Element_in_Sorted_Array.cpp

- HTML,CSS/Drawing Board/index.html
- HTML,CSS/Drawing Board/index.js
- HTML,CSS/Drawing Board/style.css
Hello, I recently made a Drawing Board while practicing DOM Manipulation : )
It allows you to fill up the canvas with whatever your creativity holds while giving options to change colors and use the eraser.
I made this using HTML, CSS and JS
It would be really great if you could accept my pull request.
> Added Drawing Board Web App to HTML, CSS

- C++/diameteroftree.cpp
- C++/floodfill.cpp
- C++/num-of-enclaves.cpp.txt
maimum of binary tree problem added
> Depth of tree

- C++/floodfill.cpp
- C++/num-of-enclaves.cpp.txt
Hi , I have added a standard graph problem to that repo 
this will help people .
> add lalit kashyap to the contributors list

- C++/diameteroftree.cpp
- C++/floodfill.cpp
- C++/num-of-enclaves.cpp.txt
here i have added a standard tree problem which is used in most of logics to solve tree problems
don't forget to add hactoberfest2022
happy coding
> Diameter of tree

- C++/maximum_subarray.cpp
Hi! 
Added a solution for a famous leetcode problem - Maximum Subarray
hope it works out. Thank you!
> Optimised solution to Maximum Subarray

- C/Reverse a string
this is a code for reversing a string using 2d array in C language.
please accept my code for hactoberfest
> Create Reverse a string

- python/Cryptography/CeaserCipher.py
- python/Cryptography/HillCipher.py
- python/Cryptography/Readme.md
- python/Cryptography/VigenereCipher.py
<h2> Contributor: Sarthak Kapaliya </h2>
<h2> Github: TheNobody-12 </h2>
<h2> Language: Python </h2>
1. Ceaser Cipher
2. Vigenere Cipher
3. Hill Cipher
1. Ceaser Cipher
```python CeaserCipher.py```
2. Vigenere Cipher
```python VigenereCipher.py```
3. Hill Cipher
```python HillCipher.py```
1. Ceaser Cipher
2. Vigenere Cipher
3. Hill Cipher
> Added Cryptographic Ciphers

- C++/LINKLIST.cpp
i have added required code for linked list kindly merge
> added code for linked list

- C++/Codeforces_Corners_Problem.cpp
Added solution to problem 'Corners' of codeforces
> Codeforces Corners Problem Solution

- C/array_of_structure.c
Hacktoberfest 2022 code contribution.
> added_array_of_structure_program

- python/Huffman_coding.py
Program Description:- Huffman Coding Algorithm Solution using Python
> Added Huffman_coding.py Program File 

- C++/Algos/SortingAlgos/MergeSort.cpp
Added merge sort algorithm in cpp using divide and conquer
> add merge sort algorithm in cpp

- C++/recursion/ApowerB.cpp
Clean code for A power B recursively in C++ for hacktoberfest2022
> A power B recursive solution in c++

- C/Patterns/pattern1.c
- C/Patterns/pattern10.c
- C/Patterns/pattern11.c
- C/Patterns/pattern12.c
- C/Patterns/pattern13.c
- C/Patterns/pattern2.c
- C/Patterns/pattern3.c
- C/Patterns/pattern4.c
- C/Patterns/pattern5.c
- C/Patterns/pattern6.c
- C/Patterns/pattern7.c
- C/Patterns/pattern8.c
- C/Patterns/pattern9.c
- C/Single Linked List/InsertAtEnd.c
- C/Single Linked List/InsertAtGiven.c
- C/Single Linked List/InsertInBeg.c
- C/Single Linked List/SearchInSorted.c
- C/Single Linked List/SearchingInSingleLL.c
- C/Single Linked List/SingleLinkedList.c
This PR adds programs related to single linked list and Important patterns in C programming language
> linked list and patterns in C

- C++/leetcode hard critical connections in a network .cpp
most optimized code please pr this request.
>  leetcode hard critical connections in a network(graph)

- Linked list in C++
Added code for implementation of linked list.
Insertion of node at beginning and end in linked list in C++
> Create Linked list in C++

- java/MAX_ARRAY.java
Problem Description:-. To divide array in parts and find out the max elements between both the array divided.
> Adding MAX_ARRAY.java Program File Asked in Codechef 5⭐ Rating 

- C++/designPatterns/creatiion Design Patterns/abstractFactory.cpp
Example of Design Patterns in C++
Added _example_ code for **abstract factory** part of **Creation design Pattern**
> Design pattren

- kotlin/ChangesVariable.kt
Thanks maintainer have reading my Pull Request.
> hactoberfest2022 to accept

- Armstrong.cpp
> created armstrong.cpp

- C++/3sum.cpp
Problem Description: 3sum problem solution file using C++
> Added 3sum.cpp program file to your repository 

- C++/basic maths/GCD_forloop.cpp
> added gcd for loop program

- C++/Sieve of Eratosthenes/segmented-sieve.cpp
- C++/Sieve of Eratosthenes/simple-sieve.cpp
I have added the cpp code for sieve, kindly review it.
> Sieve code added

- HTML,CSS/Project_1_Form.html
thanks for reading my request !
> made changes

- C/Linear Search.c
Linear Search Using C language
> Added Linear Search in C Language

- C++/search_a_2d_matrix.cpp
Solution for following problem in cpp.
> Search a 2D Matrix

- C++/Sorting/Cocktail Sort.cpp
Added the code of Cocktail Sort which is a variation of bubble sort, pls check it and merge.
> Create Cocktail Sort.cpp

- C++/print-2D-matrix-like-a-wave.cpp
This is one of the most asked problems in interviews. I added a code for it as well as the reference link for its practice.
> added print-2D-matrix-like-a-wave.cpp program with necessary details

- JS/Rest-SpreadOperators.js
Basic difference between rest operator and spread operator is demonstrated with example
> Rest-Spread Operators

- JS/CheckStrongNumber.js
This  function is used to check wether a given number is a strong number or not
> Check Strong Number

- java/fibonacci.java
Fibonacci Series using recursion in java
please accept my PR
> hacktoberfest2022

- C++/Minimum in Rotated Sorted Array.cpp
- C++/Search in Rotated Sorted Array.cpp
Solution of 2 problems based on rotated sorted array:
1. Find Minimum in Rotated Sorted Array
2. Search in Rotated Sorted Array
> Rotated Sorted Array problems

- C++/Rhombus_pattern.cpp
- C++/butterfly.cpp
- C++/floydtriangle.cpp
- C++/halfpyramid180rot.cpp
- C++/halfpyramidnum.cpp
- C++/hollowrect.cpp
- C++/invertedhalfpyramid.cpp
- C++/invertedpattern.cpp
- C++/palindromicpattern.cpp
- C++/star.cpp
C++ awesome Pattern based SOlutions . please approve it with label hacktoberfest2022 .
> Pattern Based C++ Questions

- java/Data Structures/Linked Lists/linkedlists.java
- java/Data Structures/Trees/Binary Search Tree/binarysearchTree.java
- java/Data Structures/Trees/Binary Tree/TreeTraversals.java
- java/Data Structures/Trees/Binary Tree/TreeViews.java
- java/Data Structures/Trees/Binary Tree/binarytree.java
- java/Data Structures/Trees/Binary Tree/burnBinaryTree.java
> Binary Tree Implementation and Interview Questions

- sms.py
This program can keep track of all management and billing activities in a supermarket. It holds a record of all the customers, employees, and products. It can be used to add, see details of multiple entries, and delete and update customers, employees, and products. It can also be used for creating, editing, viewing and checking out the cart by a customer with a bill containing complete customer details about the customer, date, time, and payment method for the purchase.
> Supermarket Management System

- order.py
This program helps you order food
> Order food

- python/hack1.py
A Python Program to generate passwords of your surrounding WiFi technology.
> WiFi Password Generator

- quiz.py
Quiz Project In Python .
used python function knowledge.
> 'quiz'application 

- C++/modified-game-of-nim.cpp
I have added the solution of one of famous game theory problem named modified-game-of-nim I have also attached the link of problem in case any one wants that.
> Added a new game theory problem with c++ solution

- python/Parking_space_counter.py
This is a small python file which solves the issues related to parking space.
> Parking space counter

- python/palindrome.py
Python program that checks whether the input is Palindrome or not.
> Added palindrome.py

- java/Binary_to_decimal.java
Added a java code to convert binary to decimal
> Binary to decimal conversion using Java

- C++/binary tree/Lowest Common Ancestor.cpp
Added C++ code for finding Lowest Common Ancestor of two nodes in a binary tree.
> Lowest Common Ancestor

- C++/Binary Search Tree/README.md
- C++/Binary Search Tree/checkBST.cpp
- C++/Binary Search Tree/heightBST.cpp
- C++/Binary Search Tree/implementation.cpp
- C++/Binary Search Tree/min-max1.cpp
- C++/Binary Search Tree/min-max2.cpp
I have added good documentation of Binary Search Tree considering its differences with Binary Search, Checking if a binary tree is binary search tree or not, height of a binary tree, min-max elements in binary search tree. 
Codes are tested. Please review and merge it.
> (addition) : Added new directory for Binary Search Tree

- python/LangChain/custom_agents.py
This commit introduces five new custom tools for LangChain I created:
1. math_difficulty: This is a fun tool that says math is easy!
2. random_number: A tool that generates random numbers.
3. web_page_scraper: A tool that scrapes web pages for relevant information with Beautiful Soup
4. url_shortner: A tool that shortens long URLs.
5. internet_speed: A tool that measures internet speed.
To test them out install LangChain, BeautifulSoup and OpenAI with pip.
> I created custom tools for LangChain
